### ISSUE TITLE
SharePoint Site URL not visible

### ISSUE THREAD

**Issue by Prajyotsaran** [OfficeDev/microsoft-teams-apps-attendance#14]
I am at struck at step 6 and point 6, where it ask for " Enter for newly created SharePoint URL in pop up window"
<img width="1067" alt="Issue screenshot" src="https://user-images.githubusercontent.com/62714764/77674808-1e36ef80-6fb2-11ea-8f4b-65bee495b389.png">

**Comment by Prachii2020** [comment]
As mentioned in the first step of the deployment guide to create a new team so after creating this a share point site will be generated automatically. Please use the credential through which you have created the team and  try to search for the share-point site with the same team name . Under this
you will get the share point url for your site.
