### ISSUE TITLE
The CreateSPList flow doesn't work

### ISSUE THREAD

**Issue by serlopord** [OfficeDev/microsoft-teams-apps-attendance#20]
I tried the "manual" way of creating the SP List last week and everything worked fine and I wanted to do it again today in a different domain with the Flow method and it didn't work. I have followed the steps one by one but when I run the flow it gives me this error:
Unable to process template language expressions in action 'Extracted_Tenant_Name' inputs at line '1' and column '2789': 'The template language function 'substring' parameters are out of range: 'start index' and 'length' must be non-negative integers and their sum must be no larger than the length of the string. Please see https://aka.ms/logicexpressions#substring for usage details.'.

As far as I know, I am putting the name of the Team correctly... Could anybody help, please?

**Comment by RobertDK** [comment]
I am having the same issue. 
![powerappattendenceerror](https://user-images.githubusercontent.com/64505894/80549358-3e274d80-897a-11ea-9036-7b5d9d87de7f.jpg)

**Comment by serlopord** [comment]
I am glad I am not the only one... Any solutions? It would be great to post the manual instructions back again, please. Thanks.

**Comment by tinkerslab** [comment]
Solution:
Not the most elegant solution but it worked... 
Delete the formula in the "Extracted Tenant Function" and replaced it with the manual string from the sharepoint url.
if the tenant sharepoint url is **https://uniedu.sharepoint.co**m. paste **https://uniedu** in the "Extracted Tenant function".

Before
![Capture](https://user-images.githubusercontent.com/30973127/81459301-ab2bb600-91b8-11ea-9d2a-26e8d9d508db.PNG)

After
![Annotation 2020-05-09 054754](https://user-images.githubusercontent.com/30973127/81459312-b252c400-91b8-11ea-9949-d2df5962a99a.jpg)

**Comment by serlopord** [comment]
Thank you very much for your help @tinkerslab, but I couldn't make it work... I hope they either fix it or put the "manual" instructions back...

**Comment by michelebroggi** [comment]
Same error. The workaround works for me but i'm still in error. 
Last step, "For all Sharepoint sites" - Create session Metadata list. After 15 minutes give me a bad gateway error 502

**Comment by tinkerslab** [comment]
> Same error. The workaround works for me but i'm still in error. 
> Last step, "For all Sharepoint sites" - Create session Metadata list. After 15 minutes give me a bad gateway error 502

In the last step "for all SharePoint sites" the url is assembled for the SharePoint site created earlier. check if the url is assembled correctly and matches with the url of your SharePoint site. you can also check by visiting the url assembled in the last step.

**Comment by michelebroggi** [comment]
> > Same error. The workaround works for me but i'm still in error.
> > Last step, "For all Sharepoint sites" - Create session Metadata list. After 15 minutes give me a bad gateway error 502
> 
> In the last step "for all SharePoint sites" the url is assembled for the SharePoint site created earlier. check if the url is assembled correctly and matches with the url of your SharePoint site. you can also check by visiting the url assembled in the last step.

The URL il correct
https://XXXXXXX.sharepoint.com/sites/Presenze
Altro trying to connect with the complete URL (https://XXXXXXX.sharepoint.com/sites/Presenze/_api/web/lists) returns a file

here's the error
{
  "error": {
    "code": 502,
    "source": "europe-002.azure-apim.net",
    "clientRequestId": "379e1890-754e-4593-bb15-6c100246060a",
    "message": "BadGateway",
    "innerError": {
      "message": "Elenco, sondaggio, area discussioni o raccolta documenti con il titolo specificato già esistente in questo sito Web. Scegliere un altro titolo.\r\nclientRequestId: 379e1890-754e-4593-bb15-6c100246060a\r\nserviceRequestId: 960a529f-e044-b000-ccf4-709a39ae9121",
      "status": 502,
      "source": "https://XXXXXXXX.sharepoint.com/sites/Presenze/_api/web/lists",
      "errors": [
        "-2130575342",
        "Microsoft.SharePoint.SPException"
      ]
    }
  }
}

**Comment by RobertDK** [comment]
This method worked for me. Thank you

**Comment by abbodh** [comment]
The issue will be fixed with PR https://github.com/OfficeDev/microsoft-teams-apps-attendance/pull/23
