### ISSUE TITLE
Something went wrong error when importing Package into Power Apps

### ISSUE THREAD

**Issue by rachelb423** [OfficeDev/microsoft-teams-apps-attendance#3]
When completing Step 5: Import Package in Power Apps using zip file, on Import the package zip file, we are getting the error:

![image](https://user-images.githubusercontent.com/33212427/73975803-4e341180-48e4-11ea-895d-e8978b3f0d8d.png)

Can you please help? Thank you.

**Comment by yashrajmungale** [comment]
Hi @rachelb423 , Thank you for reporting the issue. 
From your screenshot it looks like the correct package zip file is not being used during import. This is the correct [link](https://github.com/OfficeDev/microsoft-teams-apps-attendance/blob/master/Package/AttendanceApp/AttendanceApp.zip). We have updated the deployment guide too with the exact link to the package zip file. Kindly try again and let us know if this resolves your issue.

**Comment by yashrajmungale** [comment]
Hey @rachelb423,  just wanted to check with you were able to successfully deploy the app

**Comment by rachelb423** [comment]
Hey Yashraj! Haven't had a chance to try yet as I've been at GEPS this
week, but I plan to give it a shot tomorrow. Thanks for the follow up.

**Comment by yashrajmungale** [comment]
Hi @rachelb423 I am marking this issue as closed. Let us know if you are able to deploy again and if not you can create another one and we can double click from there
