### ISSUE TITLE
[Step 5] connection list cannot refresh my connection when set OneDrive for Business Connection 

### ISSUE THREAD

**Issue by mxmore** [OfficeDev/microsoft-teams-apps-attendance#4]
When completing Step 5: Import Package in Power Apps using zip file, on set connection for OneDrive for Business Connection. My connection created on pre-step cannot appear when refresh the connection list

![image](https://user-images.githubusercontent.com/13625761/74702255-67be4d00-5244-11ea-868e-8ea3a9862cb8.png)

![image](https://user-images.githubusercontent.com/13625761/74702377-d26f8880-5244-11ea-8754-9ca6c970bec6.png)

**Comment by abbodh** [comment]
hi @mxmore, during first set up you have to perform Create new connection twice i.e. one for SharePoint and another for OneDrive. Can you please confirm if below steps are followed for One Drive: 

1. Click on 'Select during import'
2. On flyout, click '+ Create new' 
3. Once redirected to connections page, click '+ New connection' 
4. In the list, select 'OneDrive for Business' 
5. Please confirm the OneDrive creation in confirmation pop up and click 'Create' 
6. Go back to Import set up page and refresh list 
7. Select the connection name and Save

**Comment by mxmore** [comment]
Thanks a lot for pointing it out. my bad to ignore the connections difference between SharePoint and OneDirve for business. Now, it is okay to import the Attendance App. 
![image](https://user-images.githubusercontent.com/13625761/74760203-05516500-52b5-11ea-8b8d-0284dccee37a.png)
