### ISSUE TITLE
AttendanceApp not work on teams

### ISSUE THREAD

**Issue by mxmore** [OfficeDev/microsoft-teams-apps-attendance#6]
I have followed the deploy guide to configure the app and imported the app into teams successfully. but the app looks not work to record the attendance. What steps I use the app is that:
1. schedule a meeting on Teams with the team we configure and import the app
2. open the AttedanceApp tab on teams
3. select according team and the duration time of the meeting. then click **Initiate** button.
4.  Join the meeting form teams.
5. No Attendance data appears on AttedanceApp page.
 
I would like to confirm if it is correct steps to use it. Please feel free to point out if any step I missed. 
Thanks so much.

![image](https://user-images.githubusercontent.com/13625761/75115783-ebd96000-569c-11ea-8ec7-9ae25abbc748.png)

![image](https://user-images.githubusercontent.com/13625761/75115726-58079400-569c-11ea-9f9d-9b7ac03d14b9.png)

**Comment by mxmore** [comment]
I still cannot get any attendance information by select date/time and Click the Initiate button.  And also no attendance record appear at SharePoint list named AttendanceRecord

![image](https://user-images.githubusercontent.com/13625761/75305032-db350f80-587f-11ea-8cfc-8eed11467c41.png)

![image](https://user-images.githubusercontent.com/13625761/75304933-8abdb200-587f-11ea-84ad-2e2a990b202c.png)

**Comment by mxmore** [comment]
Is there any suggestion for my problem? Thanks a lot ~

**Comment by delfuria** [comment]
I have the same problem !!!
Also, following the deployment guide on Step 4: Giving Permission to SharePoint List, i was not able to find the groups mentioned in the guide.

**Comment by abbodh** [comment]
@mxmore - the attendance app is able to read the "Team" where you are an owner and will read the team members for marking attendance. From the first screenshot, it seems like you are expecting the app to take attendance based on meetings which is not true. 

Also, would it be possible for you to open Power Apps Studio and see if it works there?

**Comment by abbodh** [comment]
@delfuria - the group mentioned in guide is just an example. We will look into that the fixed the language for better clarity. Can you please confirm if the permissions are added to individual teachers or you have used the PowerShell script to create a group?

**Comment by delfuria** [comment]
> Can you please confirm if the permissions are added to individual teachers or you have used the PowerShell script to create a group?

Yes i have created a group and added it to Tenants Member in SitePoint permission

**Comment by macswiney** [comment]
> > Can you please confirm if the permissions are added to individual teachers or you have used the PowerShell script to create a group?
> 
> Yes i have created a group and added it to Tenants Member in SitePoint permission

Hello:

I had the same problem and it worked after something strange :s 

I needed it to be translated to spanish, so I went to PowerApps and clicked on "Edit" and started editing the information and saved it. After that I uninstalled the app in Teams and reinstalled it ¡it works now! I dont know if that helps you but it worked for me.

Have a good one!

**Comment by jcosano** [comment]
> > > Can you please confirm if the permissions are added to individual teachers or you have used the PowerShell script to create a group?
> > 
> > 
> > Yes i have created a group and added it to Tenants Member in SitePoint permission
> 
> Hello:
> 
> I had the same problem and it worked after something strange :s
> 
> I needed it to be translated to spanish, so I went to PowerApps and clicked on "Edit" and started editing the information and saved it. After that I uninstalled the app in Teams and reinstalled it ¡it works now! I dont know if that helps you but it worked for me.
> 
> Now I get the list of students but the atendee button does not works and I get an error:
> Office365Users.UserPhoto has an invalid value for 'userId'
> 
> Have a good one!

Hola, ¿me puedes ayudar con este tema?. A mi me ocurre lo mismo y probé lo que decías... traducir las etiquetas al castellano. Aun así me sigue sin funcionar.  ¿qué hiciste en concreto? Muchas gracias por adelantado.

**Comment by mxmore** [comment]
close this issue as it looks there is some grammar logic issue on the app I sync up that time. And the issue has been fixed by fix a GUID variables setting. 

anyway, our original purpose is to export the attendance info of a meeting automatically  , but this app is a manual logic. so I will lookup for some other way to satisfy my request. 

Thanks a lots for the updating. Best wishes!
