### ISSUE TITLE
Please confirm if we need to follow the deploy guide again and again for each team(class) in a tenant?

### ISSUE THREAD

**Issue by mxmore** [OfficeDev/microsoft-teams-apps-attendance#7]
As our customer is a school, they will have many class, so from my understanding, it will need to create data source and import apps for each teams we created as the classes. 
Please confirm if I am right that we need to follow the deploy guide again and again for each teams(classes) and upload apps of each team in a tenant?

**Comment by abbodh** [comment]
Hi @mxmore , no the app is needed to be created only once in a tenant (school) and you do not need to deploy it again and again.

As the user sign in to access the application, all classes (Teams) of that particular user will be shown in the drop down. User then can select the class range and will be able to take the attendance.  

Tip : Please make sure that users accessing the app have read-write access in SharePoint and the Power Apps is shared as well.

**Comment by mxmore** [comment]
Okay, thanks for the updating. so for one tenant we just need only one SharePoint of lists to store the attendance information, right? I will test if all users has the access to the app.

**Comment by yashrajmungale** [comment]
Yes, for one tenant we need a single SharePoint list

**Comment by mxmore** [comment]
Got it! Thanks a lot for clarification!
